module.exports = {
    HQ: 1,
    GOLD: 2,
    COAL: 3,
    OIL: 4,
    IRON: 5,
    BAUXITE: 6,
    FORT: 7,
    LEAD: 8,
    SULFUR: 9,
    NITER: 10,
    FACTORY: 11,
    MILITARY: 12,
    STONE: 13,
    EXPORT: 14,
    FARM: 15,
    FIELD: 16,
    WAREHOUSE: 17,
    FOREST: 18,
    MINT: 19,
    LABORATORY: 20,
};