module.exports = {
    GOLD: 'Zlato',
    COAL: 'Uhlí',
    OIL: 'Ropa',
    IRON: 'Železo',
    BAUXITE: 'Bauxit',
    LEAD: 'Olovo',
    SULFUR: 'Síra',
    NITER: 'Ledek',
    GUNPOWDER: 'Střelný prach',
    AMMO: 'Munice',
    STONE: 'Kámen',
    WHEAT: 'Pšenice',
    ALUMINIUM: 'Hliník',
    WOOD: 'Dřevo',
};